return {
	"stevearc/conform.nvim",
	cmd = { "ConformInfo" },
	opts = {
		formatters_by_ft = {
			lua = { "stylua" },
			cpp = { "clang-format" },
			c = { "clang-format" },
			python = { "ruff_format" },
			javascript = { "prettier" },
			typescript = { "prettier" },
			typescriptreact = { "prettier" },
			javascriptreact = { "prettier" },
			angular = { "prettier" },
			go = { "gofmt" },
			haskell = { "ormolu" },
			java = { "google-java-format" },
			json = { "prettier" },
			kotlin = { "ktlint" },
			markdown = { "prettier" },
			php = { "php-cs-fixer" },
			r = { "styler" },
			ruby = { "rubocop" },
			rust = { "rustfmt" },
			sql = { "sql-formatter" },
			svelte = { "prettier" },
			tailwind = { "prettier" },
			tex = { "latexindent" },
			toml = { "taplo" },
			yaml = { "yamlfmt" },
		},
		format_on_save = false,
	},
}
